FROM python:3.9

# Install basic development tools
RUN apt update && apt install -y less man-db sudo

# Ensure default `python` user has access to `sudo`
# ARG USERNAME=python
# RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#     && chmod 0440 /etc/sudoers.d/$USERNAME

# Set `DEVCONTAINER` environment variable to help with orientation
ENV DEVCONTAINER=true

# Set custom environment
ENV TZ=Asia/Tokyo
ENV PYTHONDONTWRITEBYTECODE=1
