FROM mysql:8.0

# Install basic development tools
# RUN apt update && apt install -y less man-db sudo

# Ensure default `db` user has access to `sudo`
# ARG USERNAME=db
# RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#     && chmod 0440 /etc/sudoers.d/$USERNAME

# Set custom environment
ENV TZ=Asia/Tokyo
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=notes
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
