FROM phpmyadmin

# Install basic development tools
# RUN apt update && apt install -y less man-db sudo

# Ensure default `phpmyadmin` user has access to `sudo`
# ARG USERNAME=phpmyadmin
# RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#     && chmod 0440 /etc/sudoers.d/$USERNAME

# Set custom environment
ENV TZ=Asia/Tokyo
ENV PMA_ARBITRARY=1
ENV PMA_HOSTS=db
